### PR TITLE
Namespace the Cluster resource

### PR DESCRIPTION
**Pull request by perotinus**
/sig multicluster

In my testing, this seemed to worked fine in both aggregated and standalone modes.

/cc @pmorie @madhusudancs @font

### CODE REVIEW

**Comment by madhusudancs** [comment]
What proposal is this based on? Did we come to a consensus about this?

**Comment by perotinus** [comment]
@madhusudancs [This doc](https://docs.google.com/document/d/1rT7WnWqZdqCP3Wl-NEvEb6fyP7DbDOp_Tkpc5eA5GTI/edit) has the discussion, though it is not a formal proposal. I shared it with the SIG about three weeks ago, and haven't gotten anybody arguing strongly in favor of cluster scoping. IMO, @pmorie's arguments against the disadvantages of moving to a namespaced API were convincing enough, and the need to authorize subsets of clusters seems only to be solvable by introducing namespaces.

Part of the goal of this PR was to force a consensus. My initial intention with this code was to experiment with the namespaced API, but once the work was done and I did not discover any issues, I figured it would help move the conversation along to push the code for others to review.

**Comment by madhusudancs** [comment]
@perotinus alright makes sense. Here is my argument https://docs.google.com/a/google.com/document/d/1rT7WnWqZdqCP3Wl-NEvEb6fyP7DbDOp_Tkpc5eA5GTI/edit?disco=AAAABnJ1AWI against namespaces in CR.

**Comment by perotinus** [comment]
Closing in favor of #228, which builds on #225.

**Pull request closed without merging**
