### PR TITLE
Update bazel BUILD files

### PR DESCRIPTION
**Pull request by font**
/sig multicluster

### CODE REVIEW

**Comment by pmorie** [comment]
Seems like we need a bazel build verification step.

**Comment by font** [comment]
@pmorie There is a bazel build that is run as part of testing PRs, it just needs the `ok-to-test` label added. These missing `doc.go` files did not cause build failures.

**Comment by perotinus** [comment]
There is a script in `hack`, `hack/verify-bazel.sh`, but this hasn't been set up to run on Prow yet. It should not be that hard to add a pull job that runs all the verify scripts (and potentially some more that run things like `gofmt` and `go lint`).

**Comment by pmorie** [comment]
@perotinus Seems like the verify stuff is covered by https://github.com/kubernetes/cluster-registry/issues/23, agree?

**Comment by perotinus** [comment]
@pmorie Yes, agreed.

**Pull request merged**
